In [39]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In = torch.tensor([1.,0.], dtype=torch.float32)
Out = torch.tensor(np.array([1.,1.]) / np.sqrt(2), dtype=torch.float32)

a = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
b = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
c = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
d = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)

h = torch.rand(2,2, requires_grad=True)

def forward(x):
     return x @ h
    
def loss(y, y_pred):
    
    return ((y - y_pred)**2).mean()

X_test = torch.tensor([1.,0.], dtype=torch.float32)

learning_rate = 0.01
n_epochs = 100

for epoch in range(n_epochs):
    # predict = forward pass
    predict = forward(In)

    # loss
    l = loss(Out, predict)

    # calculate gradients = backward pass
    l.backward(retain_graph=True)
    with torch.no_grad():
        h -= learning_rate * h.grad
#         b -= learning_rate * b.grad
#         c -= learning_rate * c.grad
#         d -= learning_rate * d.grad
    
    # zero the gradients after updating
    h.grad.zero_()
#     b.grad.zero_()
#     c.grad.zero_()
#     d.grad.zero_()

    if (epoch+1) % 10 == 0:
        print(f'Epoch: {epoch+1}, h = {h}, loss = {l.item()}')

print(X_test, forward(X_test))

Epoch: 10, h = tensor([[0.7922, 0.7855],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.006824937649071217
Epoch: 20, h = tensor([[0.7841, 0.7780],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.00558216730132699
Epoch: 30, h = tensor([[0.7767, 0.7712],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.004565698094666004
Epoch: 40, h = tensor([[0.7700, 0.7651],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.0037343152798712254
Epoch: 50, h = tensor([[0.7640, 0.7595],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.003054320113733411
Epoch: 60, h = tensor([[0.7586, 0.7545],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.0024981435853987932
Epoch: 70, h = tensor([[0.7537, 0.7500],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.0020432532764971256
Epoch: 80, h = tensor([[0.7492, 0.7459],
        [0.2471, 0.1007]], requires_grad=True), loss = 0.0016711871139705181
Epoch: 90, h = tensor([[0.7452, 0.7422],
        [0.2471, 0.1

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

phi = np.random.rand() * 2*np.pi
theta = np.random.rand() * np.pi

input_vec = torch.tensor([np.sin(theta), np.cos(theta) * np.exp(1j * phi)])

# In = torch.tensor([[1.,0.],[0.,1.]], dtype=torch.float32)

h_target = torch.tensor([[1.,1.],[1.,-1]] / np.sqrt(2), dtype=torch.complex128)

Out = h_target @ input_vec
 
a = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
b = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
c = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
d = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
 
# H = torch.tensor([[a,b],[c,d]], requires_grad=True)
H = torch.rand((2,2), requires_grad = True, dtype=torch.complex128)
 
def forward(x):
     return H @ x
 
def loss(y, y_pred):
 
    return (torch.abs((y - y_pred))**2).mean()
 
# X_test = torch.tensor([1.,0.], dtype=torch.complex128)
 
learning_rate = 0.01
n_epochs = 1000
 
for epoch in range(n_epochs):
    # predict = forward pass
    predict = forward(input_vec)
 
    # loss
    l = loss(Out, predict)
 
    # calculate gradients = backward pass
    l.backward(retain_graph=True)
    with torch.no_grad():
        H -= learning_rate * H.grad
        # a -= learning_rate * a.grad
        # b -= learning_rate * b.grad
        # c -= learning_rate * c.grad
        # d -= learning_rate * d.grad
 
    # zero the gradients after updating
    # a.grad.zero_()
    # b.grad.zero_()
    # c.grad.zero_()
    # d.grad.zero_()
    H.grad.zero_()
 
    if (epoch+1) % 100 == 0:
        # print(f'Epoch: {epoch+1}, a = {a.item()}, b = {b.item()}, c = {c.item()}, d = {d.item()} loss = {l.item()}')
        print(f'Epoch: {epoch+1}, H = {H}, loss = {l.item()}')

print(Out, (forward(input_vec)))

Epoch: 100, H = tensor([[0.5648+0.1969j, 0.6630+0.3218j],
        [0.5783+0.3625j, 0.6605+0.8798j]], dtype=torch.complex128,
       requires_grad=True), loss = 0.10559428783445131
Epoch: 200, H = tensor([[0.6550+0.0721j, 0.6630+0.3218j],
        [0.6600+0.1327j, 0.6605+0.8798j]], dtype=torch.complex128,
       requires_grad=True), loss = 0.014147488350917843
Epoch: 300, H = tensor([[0.6880+0.0264j, 0.6630+0.3218j],
        [0.6898+0.0486j, 0.6605+0.8798j]], dtype=torch.complex128,
       requires_grad=True), loss = 0.0018954758893127788
Epoch: 400, H = tensor([[0.7001+0.0097j, 0.6630+0.3218j],
        [0.7008+0.0178j, 0.6605+0.8798j]], dtype=torch.complex128,
       requires_grad=True), loss = 0.0002539552433512319
Epoch: 500, H = tensor([[0.7046+0.0035j, 0.6630+0.3218j],
        [0.7048+0.0065j, 0.6605+0.8798j]], dtype=torch.complex128,
       requires_grad=True), loss = 3.402484093267292e-05
Epoch: 600, H = tensor([[0.7062+0.0013j, 0.6630+0.3218j],
        [0.7063+0.0024j, 0.6605+0.8

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

input_vec_list = []

for i in range(10):
    
    phi = np.random.rand() * 2*np.pi
    theta = np.random.rand() * np.pi
    
    input_vec = torch.tensor([np.sin(theta), np.cos(theta) * np.exp(1j * phi)])
    input_vec_list.append(input_vec)

# In = torch.tensor([[1.,0.],[0.,1.]], dtype=torch.float32)

h_target = torch.tensor([[1.,1.],[1.,-1]] / np.sqrt(2), dtype=torch.complex128)

Out = h_target @ input_vec_list
 
# a = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
# b = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
# c = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
# d = torch.tensor(1.0, dtype=torch.float32, requires_grad=True)
 
# H = torch.tensor([[a,b],[c,d]], requires_grad=True)
H = torch.rand((2,2), requires_grad = True, dtype=torch.complex128)
 
def forward(x):
     return H @ x
 
def loss(y, y_pred):
 
    return (torch.abs((y - y_pred))**2).mean()
 
# X_test = torch.tensor([1.,0.], dtype=torch.complex128)
 
learning_rate = 0.01
n_epochs = 1000
 
for epoch in range(n_epochs):
    # predict = forward pass
    predict = forward(input_vec)
 
    # loss
    l = loss(Out, predict)
 
    # calculate gradients = backward pass
    l.backward(retain_graph=True)
    with torch.no_grad():
        H -= learning_rate * H.grad
        # a -= learning_rate * a.grad
        # b -= learning_rate * b.grad
        # c -= learning_rate * c.grad
        # d -= learning_rate * d.grad
 
    # zero the gradients after updating
    # a.grad.zero_()
    # b.grad.zero_()
    # c.grad.zero_()
    # d.grad.zero_()
    H.grad.zero_()
 
    if (epoch+1) % 100 == 0:
        # print(f'Epoch: {epoch+1}, a = {a.item()}, b = {b.item()}, c = {c.item()}, d = {d.item()} loss = {l.item()}')
        print(f'Epoch: {epoch+1}, H = {H}, loss = {l.item()}')

print(Out, (forward(input_vec_list)))

TypeError: unsupported operand type(s) for @: 'Tensor' and 'list'

In [37]:
import torch

z = torch.nn.Linear(3,2,bias=False)

# x = torch.rand(1,3, dtype=torch.float32)
a = torch.tensor([1,2,3], dtype=torch.float32)
print(a)
y = z(a)

print(y)

tensor([1., 2., 3.])
tensor([ 1.0286, -1.5284], grad_fn=<SqueezeBackward4>)


In [1]:
import csv
import torch
import numpy as np
import pandas as pd

fields = ['input1', 'input2','output1', 'output2']
rows = []
h_target = torch.tensor([[1.,1.],[1.,-1]] / np.sqrt(2), dtype=torch.complex128)

for i in range(8):
    phi = np.random.rand() * 2*np.pi
    theta = np.random.rand() * np.pi
    
    input = torch.tensor([np.sin(theta), np.cos(theta) * np.exp(1j * phi)])
    output = h_target @ input

    rows.append([np.sin(theta), np.cos(theta) * np.exp(1j * phi), output[0].item(), output[1].item()])

filename = 'qubit.csv'

with open(filename, 'w') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(fields)
    csvwriter.writerows(rows)

In [137]:
import pandas as pd

df = pd.read_csv('qubit.csv')

# df = np.array(df.values, dtype=complex)


df['input1'] = df['input1'].astype(complex)
df['input2'] = df['input2'].astype(complex)
df['output1'] = df['output1'].astype(complex)
df['output2'] = df['output2'].astype(complex)

input1 = torch.tensor(df['input1'])
input2 = torch.tensor(df['input2'])

a = []

for i in range(8):
    a.append([df['input1'][i],df['input2'][i]])

# print(df.values[0])

# pd.to_numeric(df, errors = 'coerce')

In [3]:
import torch
import torch.nn as nn
import torchvision
from torch.utils.data import Dataset

num_qubits = 8

num_epochs = 100

learning_rate = 0.01

class input_vec_dataset(Dataset):
    def __init__(self):
        
        self.df = pd.read_csv('qubit.csv')
        self.df['input1'] = self.df['input1'].astype(complex)
        self.df['input2'] = self.df['input2'].astype(complex)
        self.df['output1'] = self.df['output1'].astype(complex)
        self.df['output2'] = self.df['output2'].astype(complex)

        dataset = []
        labels = []

        for i in range(num_qubits):
            dataset.append([self.df['input1'][i],self.df['input2'][i]])
            
        self.dataset = torch.tensor(dataset, dtype=torch.complex128)
        
        for i in range(num_qubits):
            labels.append([self.df['output1'][i],self.df['output2'][i]])
        
        self.labels = torch.tensor(labels, dtype=torch.complex128)
        
    def __len__(self):
        return len(self.dataset)
    
    def __getitem__(self, idx):
        return self.dataset[idx],self.labels[idx]

data_set = input_vec_dataset()

data_loader = torch.utils.data.DataLoader(data_set, batch_size=1, shuffle=True, drop_last=False)

class HModel(torch.nn.Module):
    
    def __init__(self):
        super(HModel, self).__init__()     
        self.linear = nn.Linear(2,2,bias=False, dtype=torch.complex128)
        
    def forward(self, x):
        x = self.linear(x)
        return x
    
model = HModel()

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(num_epochs):
    
    for batch, labels in data_loader:
 
        optimizer.zero_grad()
        
        outputs = model(batch)
        
        loss = criterion(torch.abs(outputs),torch.abs(labels))
        
        loss.backward()
        
        optimizer.step()
        
    if epoch % 10 == 0:
        
        print(f'epoch: {epoch}, loss: {loss}')
        
model.eval()

with torch.no_grad():

    out_data = model(torch.tensor([1,0],dtype=torch.complex128))
    print(out_data)
#     print(np.conj(out_data) * out_data) 
    print(torch.abs(out_data))

epoch: 0, loss: 0.04860856965411628
epoch: 10, loss: 0.0658094806021887
epoch: 20, loss: 0.02806612645137104
epoch: 30, loss: 0.0020061832942766863
epoch: 40, loss: 1.2770053205019303e-05
epoch: 50, loss: 6.652548483102809e-09
epoch: 60, loss: 7.409230766635755e-13
epoch: 70, loss: 7.241386871942934e-17
epoch: 80, loss: 3.001892884504121e-20
epoch: 90, loss: 2.2172146765985567e-25
tensor([ 0.5279-0.4704j, -0.7042-0.0645j], dtype=torch.complex128)
tensor([0.5000+0.j, 0.5000+0.j], dtype=torch.complex128)
tensor([0.7071, 0.7071], dtype=torch.float64)
