In [39]:
import torch
import numpy as np

#Three qubits
a = torch.tensor([1,1], dtype=torch.float64) #I took out the sqrt(2) to make it easier to look at. The same results happen with or without it
b = torch.tensor([1,0], dtype=torch.float64)
c = torch.tensor([1,0], dtype=torch.float64)

cnot = torch.tensor([[1,0,0,0],
                     [0,1,0,0],
                     [0,0,0,1],
                     [0,0,1,0]], dtype=torch.float64)

i = torch.tensor([[1,0],
                  [0,1]], dtype=torch.float64)

#This is the supposedly correct cnot gate for 3 qubits, 
#based on a comment by Ryan O'Donell on this post: 
#https://quantumcomputing.stackexchange.com/questions/4252/how-to-derive-the-cnot-matrix-for-a-3-qubit-system-where-the-control-target-qu
cnot_big = torch.tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
                         [0., 1., 0., 0., 0., 0., 0., 0.],
                         [0., 0., 1., 0., 0., 0., 0., 0.],
                         [0., 0., 0., 1., 0., 0., 0., 0.],
                         [0., 0., 0., 0., 0., 1., 0., 0.],
                         [0., 0., 0., 0., 1., 0., 0., 0.],
                         [0., 0., 0., 0., 0., 0., 0., 1.],
                         [0., 0., 0., 0., 0., 0., 1., 0.]], dtype=torch.float64)

In [40]:
cnot_wrong = torch.kron(cnot, i)
print(cnot_wrong) #Based on what I've seen online, this is incorrect

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.]], dtype=torch.float64)


In [41]:
ab = torch.kron(a,b)

ab_new = ab @ cnot

abc = torch.kron(c,ab_new)

abc_new = abc @ cnot_big

print(ab_new) #This is correct
print(abc) #This is correct
print(abc_new) #This is incorrect

#It should be [1,0,0,0,0,0,0,1]
#I've tried moving around the matrices within the torch.kron() but that doesn't seem to work
#The same results still happen if I use the cnot_wrong from above
#I don't know why this isn't working

tensor([1., 0., 0., 1.], dtype=torch.float64)
tensor([1., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)
tensor([1., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)
